Learning Numpy from here 


In [ ]:
import numpy as np
numbers = [1, 2, 3, 4, 5]
arr = np.array(numbers)
print(arr)

[1 2 3 4 5]


In [ ]:
import numpy as np
print(np.__version__)

2.4.1


In [ ]:
import numpy as np
list1=[1,3,5,7,9]
arr=np.array(list1)
print(arr)
# print(type(arr))

[1 3 5 7 9]


In [ ]:
import numpy as np
list1=[1,3,5,7,9]
list2=[2,4,6,8,10]
arr=np.array([list1,list2])
print(arr)
print(type(arr))
print(arr.ndim)

[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]
<class 'numpy.ndarray'>
2


In [ ]:
import numpy as np
list1=[1,3,5,7,9]
list2=[2,4,6,8,10]
list3=[11,13,15,17,19]
list4=[12,14,16,18,20]
arr=np.array([list1,list2, list3, list4])
print(arr)
print(type(arr))
print(arr.ndim)

[[ 1  3  5  7  9]
 [ 2  4  6  8 10]
 [11 13 15 17 19]
 [12 14 16 18 20]]
<class 'numpy.ndarray'>
2


In [ ]:
data = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
arr_2d=np.array(data)
print(f"Dimensions (ndim): {arr.ndim}") 
print(arr_2d)
print(arr_2d.shape)  
print(arr_2d.size) 
zeros_2d = np.zeros((3, 4))
ones_2d = np.ones((2, 3))

Dimensions (ndim): 2
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
9


In [ ]:
import numpy as np
list1=[1,3,5,7,9]
list2=[2,4,6,8,10]
list3=[11,13,15,17,19]
list4=[12,14,16,18,20]

arr=np.array([list1,list2, list3, list4])

print(f"Dimensions (ndim): {arr.ndim}") 
print(f"Shape: {arr.shape}")              
print(arr_2d.shape)  # Output: (3, 3)


Dimensions (ndim): 2
Shape: (4, 5)


In [ ]:
zeros = np.zeros(5)
print(zeros)

[0. 0. 0. 0. 0.]


In [ ]:
ones = np.ones(5)
print(ones)

range_arr = np.arange(15)
print(range_arr)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [ ]:
# linspace_arr = np.linspace(0, 1, 10)
# print(linspace_arr)

random_arr = np.random.rand(5)  # Random 0-1
print(random_arr)

[0.17520342 0.55538517 0.26989828 0.60726136 0.07638355]


In [ ]:
import numpy as np

random_float = np.random.rand(1, 100, 5)

print(random_float)

[[[0.08554773 0.78323578 0.62211098 0.91136378 0.38985322]
  [0.01741878 0.58559584 0.48851539 0.03171072 0.01008745]
  [0.16622301 0.60852753 0.99174994 0.05172999 0.2103802 ]
  [0.36927293 0.92218973 0.79587226 0.21821903 0.96162989]
  [0.63277468 0.1766572  0.12939965 0.77952583 0.35173927]
  [0.30293089 0.38335776 0.57457065 0.02572181 0.33342658]
  [0.91300835 0.92015519 0.51380706 0.65215594 0.25376434]
  [0.99002082 0.43982188 0.94284291 0.92005413 0.12438187]
  [0.55321425 0.13801104 0.57791433 0.61897877 0.88482432]
  [0.85721828 0.61180349 0.64160533 0.76981964 0.81691241]
  [0.46168912 0.5489114  0.16083162 0.17189636 0.34215246]
  [0.62676054 0.71117604 0.60938186 0.78408517 0.18056211]
  [0.20218727 0.77202055 0.89895354 0.84544072 0.44450372]
  [0.088169   0.74125474 0.88925959 0.05296177 0.18517051]
  [0.78541415 0.67181602 0.99132344 0.85067416 0.93981852]
  [0.36371124 0.43494153 0.26610012 0.52116225 0.05357283]
  [0.94294689 0.07298997 0.65364173 0.02661623 0.1091966

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
# result = arr + 10
# print(result)
# result = arr - 1
# print(result)
result = arr ** 2
print(result)# print(result)

[ 1  4  9 16 25]


In [ ]:
arr = np.array([1, 5, 3, 2, 4])
print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.min(arr))
print(np.max(arr))
sorted_arr = np.sort(arr)
print(sorted_arr)
arr_with_dups = np.array([1, 2, 2, 3, 3, 3])
unique = np.unique(arr_with_dups)
print(unique)

15
3.0
3.0
1.4142135623730951
1
5
[1 2 3 4 5]
[1 2 3]


In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])
print(arr[2])
print(arr[-1])
print(arr[1:4])
print(arr[::2])
print(arr[::-1])

10
30
50
[20 30 40]
[10 30 50]
[50 40 30 20 10]


In [ ]:
arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
# print(arr_2d[0, 0])
# print(arr_2d[1, 2])
# print(arr_2d[0])
# print(arr_2d[:, 0])
print(arr_2d[0:2, 1:3])

[[2 3]
 [5 6]]


In [ ]:
import numpy as np
arr = np.array([1, 2, np.nan, 4, 5, np.nan, 7])
print(arr)
print(np.isnan(arr))

[ 1.  2. nan  4.  5. nan  7.]


In [ ]:
arr_clean = arr[~np.isnan(arr)]
print(arr_clean)

[1. 2. 4. 5. 7.]


In [ ]:
nan_count = np.sum(np.isnan(arr))
print(f"Missing values: {nan_count}")


Missing values: 2


In [ ]:
arr_filled = np.where(np.isnan(arr), 0, arr)
print(arr_filled)

[1. 2. 0. 4. 5. 0. 7.]


In [ ]:
mean_value = np.nanmean(arr)
arr_filled = np.where(np.isnan(arr), mean_value, arr)
print(arr_filled)

[1.  2.  3.8 4.  5.  3.8 7. ]


In [ ]:
arr = np.array([10, 12, 15, 18, 20, 100, 22, 25])
mean = np.mean(arr)
std = np.std(arr)
outliers = np.abs(arr - mean) > 2 * std
arr_clean = arr[~outliers]
print(f"Original: {arr}")
print(f"Cleaned: {arr_clean}")

Original: [ 10  12  15  18  20 100  22  25]
Cleaned: [10 12 15 18 20 22 25]


In [ ]:
arr = np.array([1, 2, 2, 3, 3, 3, 4, 4, 5])
unique_arr = np.unique(arr)
print(unique_arr)
unique, counts = np.unique(arr, return_counts=True)
for val, count in zip(unique, counts):
    print(f"{val}: appears {count} times")


[1 2 3 4 5]
1: appears 1 times
2: appears 2 times
3: appears 3 times
4: appears 2 times
5: appears 1 times


In [ ]:
arr = np.array([10, 20, 30, 40, 50])
arr_min = np.min(arr)
arr_max = np.max(arr)
arr_normalized = (arr - arr_min) / (arr_max - arr_min)
print(arr_normalized)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
arr = np.array([10, 20, 30, 40, 50])
mean = np.mean(arr)
std = np.std(arr)
arr_standardized = (arr - mean) / std
print(arr_standardized)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [ ]:
import numpy as np
sales = np.array([100, 150, np.nan, 200, 180, 5000, 220, 190, 250, np.nan])
print(f"Original data: {sales}")
nan_mask = np.isnan(sales)
print(f"NaN values: {np.sum(nan_mask)}")
sales_no_nan = sales[~nan_mask]
mean = np.mean(sales_no_nan)
std = np.std(sales_no_nan)
outlier_mask = np.abs(sales_no_nan - mean) > 3 * std
sales_clean = sales_no_nan[~outlier_mask]
print(f"Cleaned data: {sales_clean}")
print(f"Mean: {np.mean(sales_clean):.2f}")
print(f"Std Dev: {np.std(sales_clean):.2f}")

In [ ]:
import numpy as np
temps = np.array([20, 22, 25, -999, 23, 24, 1000, 22, 21, 20])
temps_clean = np.where((temps < 0) | (temps > 50), np.nan, temps)
temps_valid = temps_clean[~np.isnan(temps_clean)]
print(f"Cleaned temperatures: {temps_valid}")
print(f"Average: {np.mean(temps_valid):.2f}°C")


In [ ]:
ratings = np.array([4.5, 3.2, 4.8, 5.1, 2.9, 4.2, 6.0, 3.8, 4.1])
ratings_clean = np.where((ratings >= 1) & (ratings <= 5), ratings, np.nan)
ratings_valid = ratings_clean[~np.isnan(ratings_clean)]
print(f"Valid ratings: {ratings_valid}")
print(f"Average rating: {np.mean(ratings_valid):.2f}")

In [ ]:
import numpy as np
sales = np.array([100, 150, -50, 200, 180, -30, 220, 190, 250, -80])
positive_sales = sales[sales > 0]
print(f"Original: {sales}")
print(f"Positive only: {positive_sales}")
print(f"Total sales: {np.sum(positive_sales)}")
print(f"Average sale: {np.mean(positive_sales):.2f}")

In [ ]:
customers = np.array([
    [1, "Ali", 5000],
    [2, "Sara", 7500],
    [1, "Ali", 5000],  
    [3, "Bob", 3200],
    [2, "Sara", 7500]  
])
unique_customers = np.unique(customers, axis=0)
print(unique_customers)

In [ ]:
import numpy as np
arr = np.genfromtxt("sales_data.csv", delimiter=",", dtype=str, skip_header=1)
print(arr)


In [ ]:
import numpy as np
data = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
np.savetxt("output.csv", data, delimiter=",", fmt="%d")
print("Saved to output.csv")

In [ ]:
import numpy as np
arr = np.genfromtxt("sales_data.csv", delimiter=",", skip_header=1)
arr_clean = arr[~np.any(np.isnan(arr), axis=1)]
np.savetxt("clean_data.csv", arr_clean, delimiter=",", fmt="%d")
print("Saved to clean_data.csv")

In [ ]:
import numpy as np
arr = np.array([10, 20, 15, 25, 30, 22, 18])
print(f"Count: {len(arr)}")
print(f"Sum: {np.sum(arr)}")
print(f"Mean: {np.mean(arr):.2f}")
print(f"Median: {np.median(arr):.2f}")
print(f"Mode: {np.bincount(arr).argmax()}")
print(f"Std Dev: {np.std(arr):.2f}")
print(f"Variance: {np.var(arr):.2f}")
print(f"Min: {np.min(arr)}")
print(f"Max: {np.max(arr)}")
print(f"Range: {np.max(arr) - np.min(arr)}")
print(f"Quartiles: {np.percentile(arr, [25, 50, 75])}")

In [3]:
sales = np.array([100, 150, 200, 250, 300])
profit = np.array([20, 35, 50, 65, 80])
correlation = np.corrcoef(sales, profit)[0, 1]
print(f"Correlation: {correlation:.3f}")
covariance = np.cov(sales, profit)[0, 1]
print(f"Covariance: {covariance:.2f}")

Correlation: 1.000
Covariance: 1875.00


In [ ]:
import numpy as np
arr = np.array([1, 2, 3])
arr = np.zeros(5)
arr = np.ones(5)
arr = np.arange(10)
arr = np.random.rand(5)
arr +=10
arr *= 2
np.sum(arr)
np.mean(arr)
np.std(arr)
arr[0]
arr[1:4]
arr[::-1]
np.isnan(arr)
arr[~np.isnan(arr)]
arr[arr > 5]
np.unique(arr)
np.mean(arr)
np.median(arr)
np.std(arr)
np.min(arr)
np.max(arr)
print

In [ ]:
import numpy as np
import time
py_list = list(range(1000000))
start = time.time()
sum(py_list)
py_time = time.time() - start
np_arr = np.arange(1000000)
start = time.time()
np.sum(np_arr)
np_time = time.time() - start
print(f"Python list: {py_time:.6f} seconds")
print(f"NumPy array: {np_time:.6f} seconds")
print(f"NumPy is {py_time/np_time:.1f}x faster!")